org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[4,)

mod_id=super_snowmen
mod_name=Super Snowmen
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.lostpatrol
mod_authors=LostPatrol_3
mod_description=Upgrade snow golems with inventories, stronger attributes, and configurable projectile replacement.
